#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XPlatMvvmLabApp.Resource", IsApplication=true)]

namespace XPlatMvvmLabApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::GalaSoft.MvvmLight.Platform.Resource.String.ApplicationName = global::XPlatMvvmLabApp.Resource.String.ApplicationName;
			global::GalaSoft.MvvmLight.Platform.Resource.String.Hello = global::XPlatMvvmLabApp.Resource.String.Hello;
			global::PresentationLib.Resource.Attribute.MvxBind = global::XPlatMvvmLabApp.Resource.Attribute.MvxBind;
			global::PresentationLib.Resource.Attribute.MvxDropDownItemTemplate = global::XPlatMvvmLabApp.Resource.Attribute.MvxDropDownItemTemplate;
			global::PresentationLib.Resource.Attribute.MvxItemTemplate = global::XPlatMvvmLabApp.Resource.Attribute.MvxItemTemplate;
			global::PresentationLib.Resource.Attribute.MvxSource = global::XPlatMvvmLabApp.Resource.Attribute.MvxSource;
			global::PresentationLib.Resource.Drawable.Icon = global::XPlatMvvmLabApp.Resource.Drawable.Icon;
			global::PresentationLib.Resource.Id.MvxBindingTagUnique = global::XPlatMvvmLabApp.Resource.Id.MvxBindingTagUnique;
			global::PresentationLib.Resource.Id.myButton = global::XPlatMvvmLabApp.Resource.Id.myButton;
			global::PresentationLib.Resource.Layout.main = global::XPlatMvvmLabApp.Resource.Layout.main;
			global::PresentationLib.Resource.String.ApplicationName = global::XPlatMvvmLabApp.Resource.String.ApplicationName;
			global::PresentationLib.Resource.String.Hello = global::XPlatMvvmLabApp.Resource.String.Hello;
			global::PresentationLib.Resource.String.hello = global::XPlatMvvmLabApp.Resource.String.hello;
			global::PresentationLib.Resource.String.library_name = global::XPlatMvvmLabApp.Resource.String.library_name;
			global::PresentationLib.Resource.Styleable.MvxBinding = global::XPlatMvvmLabApp.Resource.Styleable.MvxBinding;
			global::PresentationLib.Resource.Styleable.MvxBinding_MvxBind = global::XPlatMvvmLabApp.Resource.Styleable.MvxBinding_MvxBind;
			global::PresentationLib.Resource.Styleable.MvxImageView = global::XPlatMvvmLabApp.Resource.Styleable.MvxImageView;
			global::PresentationLib.Resource.Styleable.MvxImageView_MvxSource = global::XPlatMvvmLabApp.Resource.Styleable.MvxImageView_MvxSource;
			global::PresentationLib.Resource.Styleable.MvxListView = global::XPlatMvvmLabApp.Resource.Styleable.MvxListView;
			global::PresentationLib.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::XPlatMvvmLabApp.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::PresentationLib.Resource.Styleable.MvxListView_MvxItemTemplate = global::XPlatMvvmLabApp.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int MvxDropDownItemTemplate = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int MvxItemTemplate = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int MvxSource = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvxBindingTagUnique = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int myButton = 2130968577;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050003
			public const int ApplicationName = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int Hello = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771971};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
